[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gcp-oidc"
version = "0.1.0"
description = "FastAPI application for working with Google Cloud OIDC."
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
]
